openapi: 3.0.3
info:
  title: MyWallet API
  description: |
    API complète pour l'application MyWallet - Gestion des finances personnelles
    Cette API permet de gérer les utilisateurs, les transactions et les abonnements.
  version: 1.0.0
  contact:
    name: Support MyWallet
    email: support@mywallet.com

servers:
  - url: http://localhost:3000/api
    description: Serveur de développement
  - url: https://mywallet-backend-myve.onrender.com/api
    description: Serveur de production

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        username:
          type: string
          example: "johndoe"
        email:
          type: string
          format: email
          example: "john@example.com"
        profileImage:
          type: string
          example: "https://api.dicebear.com/7.x/avataaars/svg?seed=johndoe"
        createdAt:
          type: string
          format: date-time
          example: "2024-01-15T10:30:00Z"
      required:
        - id
        - username
        - email

    AuthResponse:
      type: object
      properties:
        message:
          type: string
          example: "Utilisateur créé avec succès"
        token:
          type: string
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        user:
          $ref: '#/components/schemas/User'

    Error:
      type: object
      properties:
        message:
          type: string
          example: "Erreur interne du serveur"
        errors:
          type: array
          items:
            type: string
          example: ["Le libellé est requis", "Format de date invalide"]

    Transaction:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        user_id:
          type: string
          format: uuid
        title:
          type: string
          example: "Salaire"
        amount:
          type: number
          format: float
          example: 1500.50
        category:
          type: string
          example: "Revenu"
        created_at:
          type: string
          format: date
          example: "2024-01-15"
      required:
        - title
        - amount
        - category

    Subscription:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        user_id:
          type: string
          format: uuid
        label:
          type: string
          example: "Netflix"
        amount:
          type: number
          format: float
          example: 12.99
        date:
          type: string
          format: date
          example: "2024-01-15"
        recurrence:
          type: string
          enum: [monthly, yearly, weekly]
          example: "monthly"
        rating:
          type: integer
          minimum: 1
          maximum: 5
          example: 4
        image_url:
          type: string
          nullable: true
          example: "https://res.cloudinary.com/.../netflix.jpg"
        created_at:
          type: string
          format: date-time
          example: "2024-01-15T10:30:00Z"
      required:
        - label
        - amount
        - date
        - recurrence
        - rating

    TransactionSummary:
      type: object
      properties:
        balance:
          type: number
          format: float
          example: 1500.50
        income:
          type: number
          format: float
          example: 2000.00
        expenses:
          type: number
          format: float
          example: -499.50

    SubscriptionSummary:
      type: object
      properties:
        total:
          type: number
          format: float
          example: 45.97
        count:
          type: integer
          example: 3

  parameters:
    SubscriptionId:
      name: id
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: ID de l'abonnement
    TransactionId:
      name: id
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: ID de la transaction

paths:
  /health:
    get:
      summary: Vérification de l'état du serveur
      description: Endpoint de santé pour vérifier que l'API fonctionne correctement
      tags:
        - Santé
      responses:
        '200':
          description: Serveur fonctionne normalement
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "OK"
                  message:
                    type: string
                    example: "Serveur fonctionne"
                  timestamp:
                    type: string
                    format: date-time
                  environment:
                    type: string
                    example: "development"

  /auth/register:
    post:
      summary: Inscription d'un nouvel utilisateur
      description: Crée un nouveau compte utilisateur avec nom d'utilisateur, email et mot de passe
      tags:
        - Authentification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "johndoe"
                  minLength: 3
                email:
                  type: string
                  format: email
                  example: "john@example.com"
                password:
                  type: string
                  example: "password123"
                  minLength: 6
              required:
                - username
                - email
                - password
      responses:
        '201':
          description: Utilisateur créé avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Données d'inscription invalides
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Erreur interne du serveur

  /auth/login:
    post:
      summary: Connexion utilisateur
      description: Authentifie un utilisateur avec son email et mot de passe
      tags:
        - Authentification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: "john@example.com"
                password:
                  type: string
                  example: "password123"
              required:
                - email
                - password
      responses:
        '200':
          description: Connexion réussie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Identifiants invalides
        '429':
          description: Trop de tentatives de connexion
        '500':
          description: Erreur interne du serveur

  /transactions:
    get:
      summary: Récupère toutes les transactions de l'utilisateur
      description: Retourne la liste de toutes les transactions de l'utilisateur authentifié
      tags:
        - Transactions
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Liste des transactions récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '401':
          description: Non authentifié
        '500':
          description: Erreur interne du serveur

    post:
      summary: Crée une nouvelle transaction
      description: Ajoute une nouvelle transaction pour l'utilisateur authentifié
      tags:
        - Transactions
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "Salaire"
                amount:
                  type: number
                  format: float
                  example: 1500.50
                category:
                  type: string
                  example: "Revenu"
              required:
                - title
                - amount
                - category
      responses:
        '201':
          description: Transaction créée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          description: Données de transaction invalides
        '401':
          description: Non authentifié
        '500':
          description: Erreur interne du serveur

  /transactions/summary:
    get:
      summary: Récupère le résumé financier
      description: Retourne le solde, les revenus et les dépenses de l'utilisateur
      tags:
        - Transactions
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Résumé récupéré avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionSummary'
        '401':
          description: Non authentifié
        '500':
          description: Erreur interne du serveur

  /transactions/{id}:
    delete:
      summary: Supprime une transaction
      description: Supprime une transaction spécifique de l'utilisateur authentifié
      tags:
        - Transactions
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/TransactionId'
      responses:
        '200':
          description: Transaction supprimée avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Transaction deleted successfully"
        '400':
          description: ID de transaction invalide
        '401':
          description: Non authentifié
        '404':
          description: Transaction non trouvée
        '500':
          description: Erreur interne du serveur

  /subscriptions:
    get:
      summary: Récupère tous les abonnements de l'utilisateur
      description: Retourne la liste de tous les abonnements de l'utilisateur authentifié
      tags:
        - Abonnements
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Liste des abonnements récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subscription'
        '401':
          description: Non authentifié
        '500':
          description: Erreur interne du serveur

    post:
      summary: Crée un nouvel abonnement
      description: Ajoute un nouvel abonnement pour l'utilisateur authentifié
      tags:
        - Abonnements
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                label:
                  type: string
                  example: "Netflix"
                amount:
                  type: number
                  format: float
                  example: 12.99
                date:
                  type: string
                  format: date
                  example: "2024-01-15"
                recurrence:
                  type: string
                  enum: [monthly, yearly, weekly]
                  example: "monthly"
                rating:
                  type: integer
                  minimum: 1
                  maximum: 5
                  example: 4
                image:
                  type: string
                  description: Image en base64 (optionnelle)
                  example: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQ..."
              required:
                - label
                - amount
                - date
                - recurrence
                - rating
      responses:
        '201':
          description: Abonnement créé avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Abonnement créé avec succès"
                  subscription:
                    $ref: '#/components/schemas/Subscription'
        '400':
          description: Données d'abonnement invalides
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Non authentifié
        '500':
          description: Erreur interne du serveur

  /subscriptions/summary:
    get:
      summary: Récupère le résumé des abonnements
      description: Retourne le total des montants et le nombre d'abonnements de l'utilisateur
      tags:
        - Abonnements
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Résumé récupéré avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionSummary'
        '401':
          description: Non authentifié
        '500':
          description: Erreur interne du serveur

  /subscriptions/{id}:
    delete:
      summary: Supprime un abonnement
      description: Supprime un abonnement spécifique de l'utilisateur authentifié
      tags:
        - Abonnements
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/SubscriptionId'
      responses:
        '200':
          description: Abonnement supprimé avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Abonnement supprimé avec succès"
                  deletedId:
                    type: string
                    format: uuid
        '400':
          description: ID d'abonnement invalide
        '401':
          description: Non authentifié
        '404':
          description: Abonnement non trouvé
        '500':
          description: Erreur interne du serveur

tags:
  - name: Authentification
    description: Opérations d'inscription et de connexion
  - name: Transactions
    description: Gestion des transactions financières
  - name: Abonnements
    description: Gestion des abonnements récurrents
  - name: Santé
    description: Endpoints de monitoring