openapi: 3.0.3
info:
  title: e-Track API
  description: |
    API de gestion financière pour suivre les transactions et abonnements.
    - **Authentification** : Toutes les routes (sauf /auth) nécessitent un token JWT dans le header Authorization
    - **Rate Limiting** : Toutes les routes sont soumises à une limitation de requêtes
  version: 1.0.0
  contact:
    name: Support API
    email: support@etrack.com

servers:
  - url: http://localhost:3000/api
    description: Serveur de développement
  - url: https://votre-domaine.com/api
    description: Serveur de production

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        username:
          type: string
          example: "johndoe"
        email:
          type: string
          format: email
          example: "john@example.com"
        profileImage:
          type: string
          example: "https://api.dicebear.com/7.x/avataaars/svg?seed=johndoe"
        createdAt:
          type: string
          format: date-time
          example: "2024-01-15T10:30:00Z"
    
    AuthResponse:
      type: object
      properties:
        message:
          type: string
          example: "Utilisateur créé avec succès."
        token:
          type: string
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        user:
          $ref: '#/components/schemas/User'
    
    Error:
      type: object
      properties:
        message:
          type: string
          example: "Erreur interne du serveur"
        errors:
          type: array
          items:
            type: string
          example: ["Le libellé est requis", "Le montant doit être un nombre positif"]
    
    Subscription:
      type: object
      properties:
        id:
          type: integer
          example: 1
        user_id:
          type: integer
          example: 1
        label:
          type: string
          example: "Netflix"
        amount:
          type: number
          format: float
          example: 12.99
        date:
          type: string
          format: date
          example: "2024-01-15"
        recurrence:
          type: string
          enum: [monthly, yearly, weekly]
          example: "monthly"
        rating:
          type: integer
          minimum: 1
          maximum: 5
          example: 4
        image_url:
          type: string
          nullable: true
          example: "https://res.cloudinary.com/.../image.jpg"
        created_at:
          type: string
          format: date-time
          example: "2024-01-15T10:30:00Z"
    
    SubscriptionCreate:
      type: object
      required:
        - label
        - amount
        - date
        - recurrence
        - rating
      properties:
        label:
          type: string
          example: "Netflix"
        amount:
          type: number
          format: float
          example: 12.99
        date:
          type: string
          format: date
          example: "2024-01-15"
        recurrence:
          type: string
          enum: [monthly, yearly, weekly]
          example: "monthly"
        rating:
          type: integer
          minimum: 1
          maximum: 5
          example: 4
        image:
          type: string
          description: "Image en base64 (optionnelle)"
          example: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQ..."
    
    SubscriptionSummary:
      type: object
      properties:
        message:
          type: string
          example: "Récupération du résumé réussie"
        total:
          type: number
          format: float
          example: 45.97
        count:
          type: integer
          example: 3
    
    Transaction:
      type: object
      properties:
        id:
          type: integer
          example: 1
        user_id:
          type: integer
          example: 1
        title:
          type: string
          example: "Salaire"
        amount:
          type: number
          format: float
          example: 2500.00
        category:
          type: string
          example: "Revenu"
        created_at:
          type: string
          format: date-time
          example: "2024-01-15T10:30:00Z"
    
    TransactionCreate:
      type: object
      required:
        - title
        - amount
        - category
      properties:
        title:
          type: string
          example: "Salaire"
        amount:
          type: number
          format: float
          example: 2500.00
        category:
          type: string
          example: "Revenu"
    
    TransactionSummary:
      type: object
      properties:
        balance:
          type: number
          format: float
          example: 1500.00
        income:
          type: number
          format: float
          example: 2500.00
        expenses:
          type: number
          format: float
          example: -1000.00

security:
  - bearerAuth: []

paths:
  /health:
    get:
      summary: Vérification de l'état du serveur
      tags:
        - Health
      responses:
        '200':
          description: Serveur fonctionne correctement
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "OK"
                  message:
                    type: string
                    example: "Serveur fonctionne"
                  timestamp:
                    type: string
                    format: date-time
                  environment:
                    type: string
                    example: "development"

  /auth/register:
    post:
      summary: Inscription d'un nouvel utilisateur
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - email
                - password
              properties:
                username:
                  type: string
                  minLength: 3
                  example: "johndoe"
                email:
                  type: string
                  format: email
                  example: "john@example.com"
                password:
                  type: string
                  minLength: 6
                  example: "password123"
      responses:
        '201':
          description: Utilisateur créé avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Données invalides ou utilisateur existe déjà
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/login:
    post:
      summary: Connexion utilisateur
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: "john@example.com"
                password:
                  type: string
                  example: "password123"
      responses:
        '200':
          description: Connexion réussie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Identifiants invalides
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: Trop de tentatives de connexion
        '500':
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /subscriptions:
    get:
      summary: Récupérer tous les abonnements de l'utilisateur
      tags:
        - Subscriptions
      responses:
        '200':
          description: Liste des abonnements récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subscription'
        '401':
          description: Non authentifié
        '500':
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    post:
      summary: Créer un nouvel abonnement
      tags:
        - Subscriptions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscriptionCreate'
      responses:
        '201':
          description: Abonnement créé avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Abonnement créé avec succès"
                  subscription:
                    $ref: '#/components/schemas/Subscription'
        '400':
          description: Données de validation invalides
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Non authentifié
        '500':
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /subscriptions/{id}:
    delete:
      summary: Supprimer un abonnement
      tags:
        - Subscriptions
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
          description: ID de l'abonnement à supprimer
      responses:
        '200':
          description: Abonnement supprimé avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Abonnement supprimé avec succès"
                  deletedId:
                    type: integer
                    example: 1
        '400':
          description: ID d'abonnement invalide
        '401':
          description: Non authentifié
        '404':
          description: Abonnement non trouvé
        '500':
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /subscriptions/summary:
    get:
      summary: Récupérer le résumé des abonnements
      tags:
        - Subscriptions
      responses:
        '200':
          description: Résumé récupéré avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionSummary'
        '401':
          description: Non authentifié
        '500':
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /transactions:
    get:
      summary: Récupérer toutes les transactions de l'utilisateur
      tags:
        - Transactions
      responses:
        '200':
          description: Liste des transactions récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '401':
          description: Non authentifié
        '500':
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    post:
      summary: Créer une nouvelle transaction
      tags:
        - Transactions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionCreate'
      responses:
        '201':
          description: Transaction créée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          description: Données invalides
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Non authentifié
        '500':
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /transactions/{id}:
    delete:
      summary: Supprimer une transaction
      tags:
        - Transactions
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
          description: ID de la transaction à supprimer
      responses:
        '200':
          description: Transaction supprimée avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Transaction deleted successfully"
        '400':
          description: ID de transaction invalide
        '401':
          description: Non authentifié
        '404':
          description: Transaction non trouvée
        '500':
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /transactions/summary:
    get:
      summary: Récupérer le résumé financier
      tags:
        - Transactions
      responses:
        '200':
          description: Résumé financier récupéré avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionSummary'
        '401':
          description: Non authentifié
        '500':
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

tags:
  - name: Health
    description: Endpoints de vérification de l'état du serveur
  - name: Authentication
    description: Endpoints d'authentification des utilisateurs
  - name: Subscriptions
    description: Gestion des abonnements
  - name: Transactions
    description: Gestion des transactions financières