openapi: 3.0.0
info:
  title: MedRemind API
  description: API de gestion des médicaments et rappels de prise
  version: 1.0.0
  contact:
    name: Support API
    email: support@medremind.com

servers:
  - url: http://localhost:3000/api
    description: Serveur de développement
  - url: https://votre-domaine.com/api
    description: Serveur de production

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Utilisez un token JWT de Clerk pour l'authentification

  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        clerk_user_id:
          type: string
          example: "user_123456789"
        email:
          type: string
          format: email
          example: "user@example.com"
        expo_push_token:
          type: string
          nullable: true
          example: "ExponentPushToken[xxxxxxxxxxxxxxxxxxxxxx]"
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Medication:
      type: object
      required:
        - name
        - dosage
        - times
        - start_date
        - duration
        - color
      properties:
        id:
          type: integer
          example: 1
        user_id:
          type: integer
          example: 1
        name:
          type: string
          example: "Paracétamol"
        dosage:
          type: string
          example: "500mg"
        times:
          type: array
          items:
            type: string
            example: "08:00"
          example: ["08:00", "20:00"]
        start_date:
          type: string
          format: date
          example: "2024-01-15"
        duration:
          type: string
          example: "30 days"
        color:
          type: string
          pattern: '^#[0-9A-Fa-f]{6}$'
          example: "#3B82F6"
        reminder_enabled:
          type: boolean
          default: true
        current_supply:
          type: integer
          default: 0
          example: 20
        total_supply:
          type: integer
          default: 0
          example: 30
        refill_at:
          type: integer
          default: 0
          example: 5
        refill_reminder:
          type: boolean
          default: false
        last_refill_date:
          type: string
          format: date
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    DoseHistory:
      type: object
      required:
        - medication_id
        - taken
        - timestamp
      properties:
        id:
          type: integer
          example: 1
        user_id:
          type: integer
          example: 1
        medication_id:
          type: integer
          example: 1
        timestamp:
          type: string
          format: date-time
          example: "2024-01-15T08:00:00Z"
        taken:
          type: boolean
          example: true
        medication_name:
          type: string
          example: "Paracétamol"
        dosage:
          type: string
          example: "500mg"
        color:
          type: string
          example: "#3B82F6"
        created_at:
          type: string
          format: date-time

    PushTokenRequest:
      type: object
      required:
        - expoPushToken
      properties:
        expoPushToken:
          type: string
          example: "ExponentPushToken[xxxxxxxxxxxxxxxxxxxxxx]"

    TestNotificationRequest:
      type: object
      required:
        - medicationId
      properties:
        medicationId:
          type: integer
          example: 1

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Internal server error"

  responses:
    Unauthorized:
      description: Non authentifié
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    NotFound:
      description: Ressource non trouvée
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    ValidationError:
      description: Données invalides
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

security:
  - BearerAuth: []

paths:
  /health:
    get:
      summary: Health check
      description: Vérifie l'état du serveur
      tags:
        - System
      responses:
        '200':
          description: Serveur opérationnel
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "OK"
                  timestamp:
                    type: string
                    format: date-time
                  service:
                    type: string
                    example: "MedRemind API"

  /medications:
    get:
      summary: Récupérer tous les médicaments de l'utilisateur
      tags:
        - Medications
      responses:
        '200':
          description: Liste des médicaments récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Medication'
        '500':
          $ref: '#/components/responses/InternalServerError'

    post:
      summary: Créer un nouveau médicament
      tags:
        - Medications
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Medication'
      responses:
        '201':
          description: Médicament créé avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Medication'
        '400':
          $ref: '#/components/responses/ValidationError'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /medications/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: ID du médicament

    put:
      summary: Mettre à jour un médicament
      tags:
        - Medications
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                dosage:
                  type: string
                times:
                  type: array
                  items:
                    type: string
                start_date:
                  type: string
                  format: date
                duration:
                  type: string
                color:
                  type: string
                reminder_enabled:
                  type: boolean
                current_supply:
                  type: integer
                total_supply:
                  type: integer
                refill_at:
                  type: integer
                refill_reminder:
                  type: boolean
                last_refill_date:
                  type: string
                  format: date
      responses:
        '200':
          description: Médicament mis à jour avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Medication'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    delete:
      summary: Supprimer un médicament
      tags:
        - Medications
      responses:
        '200':
          description: Médicament supprimé avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Medication deleted successfully"
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /dose-history:
    get:
      summary: Récupérer l'historique des prises
      tags:
        - Dose History
      parameters:
        - name: startDate
          in: query
          schema:
            type: string
            format: date
          description: Date de début (format YYYY-MM-DD)
        - name: endDate
          in: query
          schema:
            type: string
            format: date
          description: Date de fin (format YYYY-MM-DD)
        - name: medicationId
          in: query
          schema:
            type: integer
          description: Filtrer par ID de médicament
      responses:
        '200':
          description: Historique récupéré avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DoseHistory'
        '500':
          $ref: '#/components/responses/InternalServerError'

    post:
      summary: Enregistrer une prise de médicament
      tags:
        - Dose History
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - medicationId
                - taken
                - timestamp
              properties:
                medicationId:
                  type: integer
                  example: 1
                taken:
                  type: boolean
                  example: true
                timestamp:
                  type: string
                  format: date-time
                  example: "2024-01-15T08:00:00Z"
      responses:
        '201':
          description: Prise enregistrée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DoseHistory'
        '404':
          description: Médicament non trouvé
        '500':
          $ref: '#/components/responses/InternalServerError'

  /dose-history/today:
    get:
      summary: Récupérer les prises du jour
      tags:
        - Dose History
      responses:
        '200':
          description: Prises du jour récupérées avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DoseHistory'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /notifications/register-token:
    post:
      summary: Enregistrer un token Expo Push
      tags:
        - Notifications
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PushTokenRequest'
      responses:
        '200':
          description: Token enregistré avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
        '400':
          description: Token Expo requis
        '500':
          $ref: '#/components/responses/InternalServerError'

  /notifications/test:
    post:
      summary: Tester une notification
      tags:
        - Notifications
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestNotificationRequest'
      responses:
        '200':
          description: Notification envoyée avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  ticket:
                    type: object
        '404':
          description: Médicament non trouvé
        '500':
          $ref: '#/components/responses/InternalServerError'